
package services;

import javax.faces.context.FacesContext;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
public class UltimateFestivalOrganizer
        extends Service {

    private final static URL ULTIMATEFESTIVALORGANIZER_WSDL_LOCATION;
    private final static WebServiceException ULTIMATEFESTIVALORGANIZER_EXCEPTION;
    private final static QName ULTIMATEFESTIVALORGANIZER_QNAME = new QName("http://andipaetzold.de/", "UltimateFestivalOrganizer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String WsdlLocation = FacesContext.getCurrentInstance().getExternalContext().getInitParameter("WsdlLocation");
            url = new URL(WsdlLocation);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ULTIMATEFESTIVALORGANIZER_WSDL_LOCATION = url;
        ULTIMATEFESTIVALORGANIZER_EXCEPTION = e;
    }

    public UltimateFestivalOrganizer() {
        super(__getWsdlLocation(), ULTIMATEFESTIVALORGANIZER_QNAME);
    }

    public UltimateFestivalOrganizer(WebServiceFeature... features) {
        super(__getWsdlLocation(), ULTIMATEFESTIVALORGANIZER_QNAME, features);
    }

    public UltimateFestivalOrganizer(URL wsdlLocation) {
        super(wsdlLocation, ULTIMATEFESTIVALORGANIZER_QNAME);
    }

    public UltimateFestivalOrganizer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ULTIMATEFESTIVALORGANIZER_QNAME, features);
    }

    public UltimateFestivalOrganizer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UltimateFestivalOrganizer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns UltimateFestivalOrganizerSoap
     */
    @WebEndpoint(name = "UltimateFestivalOrganizerSoap")
    public UltimateFestivalOrganizerSoap getUltimateFestivalOrganizerSoap() {
        return super.getPort(new QName("http://andipaetzold.de/", "UltimateFestivalOrganizerSoap"), UltimateFestivalOrganizerSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UltimateFestivalOrganizerSoap
     */
    @WebEndpoint(name = "UltimateFestivalOrganizerSoap")
    public UltimateFestivalOrganizerSoap getUltimateFestivalOrganizerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://andipaetzold.de/", "UltimateFestivalOrganizerSoap"), UltimateFestivalOrganizerSoap.class, features);
    }

    /**
     * @return returns UltimateFestivalOrganizerSoap
     */
    @WebEndpoint(name = "UltimateFestivalOrganizerSoap12")
    public UltimateFestivalOrganizerSoap getUltimateFestivalOrganizerSoap12() {
        return super.getPort(new QName("http://andipaetzold.de/", "UltimateFestivalOrganizerSoap12"), UltimateFestivalOrganizerSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UltimateFestivalOrganizerSoap
     */
    @WebEndpoint(name = "UltimateFestivalOrganizerSoap12")
    public UltimateFestivalOrganizerSoap getUltimateFestivalOrganizerSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://andipaetzold.de/", "UltimateFestivalOrganizerSoap12"), UltimateFestivalOrganizerSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ULTIMATEFESTIVALORGANIZER_EXCEPTION != null) {
            throw ULTIMATEFESTIVALORGANIZER_EXCEPTION;
        }
        return ULTIMATEFESTIVALORGANIZER_WSDL_LOCATION;
    }

}
