
package services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UltimateFestivalOrganizerSoap", targetNamespace = "http://andipaetzold.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UltimateFestivalOrganizerSoap {


    /**
     * 
     * @param id
     * @return
     *     returns services.Country
     */
    @WebMethod(operationName = "GetCountryById", action = "http://andipaetzold.de/GetCountryById")
    @WebResult(name = "GetCountryByIdResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetCountryById", targetNamespace = "http://andipaetzold.de/", className = "services.GetCountryById")
    @ResponseWrapper(localName = "GetCountryByIdResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetCountryByIdResponse")
    public Country getCountryById(
        @WebParam(name = "id", targetNamespace = "http://andipaetzold.de/")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns services.Category
     */
    @WebMethod(operationName = "GetCategoryById", action = "http://andipaetzold.de/GetCategoryById")
    @WebResult(name = "GetCategoryByIdResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetCategoryById", targetNamespace = "http://andipaetzold.de/", className = "services.GetCategoryById")
    @ResponseWrapper(localName = "GetCategoryByIdResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetCategoryByIdResponse")
    public Category getCategoryById(
        @WebParam(name = "id", targetNamespace = "http://andipaetzold.de/")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns services.Artist
     */
    @WebMethod(operationName = "GetArtistById", action = "http://andipaetzold.de/GetArtistById")
    @WebResult(name = "GetArtistByIdResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetArtistById", targetNamespace = "http://andipaetzold.de/", className = "services.GetArtistById")
    @ResponseWrapper(localName = "GetArtistByIdResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetArtistByIdResponse")
    public Artist getArtistById(
        @WebParam(name = "id", targetNamespace = "http://andipaetzold.de/")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns services.Venue
     */
    @WebMethod(operationName = "GetVenueById", action = "http://andipaetzold.de/GetVenueById")
    @WebResult(name = "GetVenueByIdResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetVenueById", targetNamespace = "http://andipaetzold.de/", className = "services.GetVenueById")
    @ResponseWrapper(localName = "GetVenueByIdResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetVenueByIdResponse")
    public Venue getVenueById(
        @WebParam(name = "id", targetNamespace = "http://andipaetzold.de/")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns services.Performance
     */
    @WebMethod(operationName = "GetPerformanceById", action = "http://andipaetzold.de/GetPerformanceById")
    @WebResult(name = "GetPerformanceByIdResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetPerformanceById", targetNamespace = "http://andipaetzold.de/", className = "services.GetPerformanceById")
    @ResponseWrapper(localName = "GetPerformanceByIdResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetPerformanceByIdResponse")
    public Performance getPerformanceById(
        @WebParam(name = "id", targetNamespace = "http://andipaetzold.de/")
        int id);

    /**
     * 
     * @return
     *     returns services.ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesWithPerformances", action = "http://andipaetzold.de/GetDatesWithPerformances")
    @WebResult(name = "GetDatesWithPerformancesResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetDatesWithPerformances", targetNamespace = "http://andipaetzold.de/", className = "services.GetDatesWithPerformances")
    @ResponseWrapper(localName = "GetDatesWithPerformancesResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetDatesWithPerformancesResponse")
    public ArrayOfDateTime getDatesWithPerformances();

    /**
     * 
     * @return
     *     returns services.ArrayOfPerformance
     */
    @WebMethod(operationName = "GetAllPerformances", action = "http://andipaetzold.de/GetAllPerformances")
    @WebResult(name = "GetAllPerformancesResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetAllPerformances", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllPerformances")
    @ResponseWrapper(localName = "GetAllPerformancesResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllPerformancesResponse")
    public ArrayOfPerformance getAllPerformances();

    /**
     * 
     * @return
     *     returns services.ArrayOfArtist
     */
    @WebMethod(operationName = "GetAllArtists", action = "http://andipaetzold.de/GetAllArtists")
    @WebResult(name = "GetAllArtistsResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetAllArtists", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllArtists")
    @ResponseWrapper(localName = "GetAllArtistsResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllArtistsResponse")
    public ArrayOfArtist getAllArtists();

    /**
     * 
     * @return
     *     returns services.ArrayOfCategory
     */
    @WebMethod(operationName = "GetAllCategories", action = "http://andipaetzold.de/GetAllCategories")
    @WebResult(name = "GetAllCategoriesResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetAllCategories", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllCategories")
    @ResponseWrapper(localName = "GetAllCategoriesResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllCategoriesResponse")
    public ArrayOfCategory getAllCategories();

    /**
     * 
     * @return
     *     returns services.ArrayOfCountry
     */
    @WebMethod(operationName = "GetAllCountries", action = "http://andipaetzold.de/GetAllCountries")
    @WebResult(name = "GetAllCountriesResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetAllCountries", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllCountries")
    @ResponseWrapper(localName = "GetAllCountriesResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllCountriesResponse")
    public ArrayOfCountry getAllCountries();

    /**
     * 
     * @return
     *     returns services.ArrayOfVenue
     */
    @WebMethod(operationName = "GetAllVenues", action = "http://andipaetzold.de/GetAllVenues")
    @WebResult(name = "GetAllVenuesResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetAllVenues", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllVenues")
    @ResponseWrapper(localName = "GetAllVenuesResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllVenuesResponse")
    public ArrayOfVenue getAllVenues();

    /**
     * 
     * @return
     *     returns services.ArrayOfArtist
     */
    @WebMethod(operationName = "GetAllButDeletedArtists", action = "http://andipaetzold.de/GetAllButDeletedArtists")
    @WebResult(name = "GetAllButDeletedArtistsResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetAllButDeletedArtists", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllButDeletedArtists")
    @ResponseWrapper(localName = "GetAllButDeletedArtistsResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetAllButDeletedArtistsResponse")
    public ArrayOfArtist getAllButDeletedArtists();

    /**
     * 
     * @param dateTime
     * @return
     *     returns services.ArrayOfPerformance
     */
    @WebMethod(operationName = "GetPerformancesByDate", action = "http://andipaetzold.de/GetPerformancesByDate")
    @WebResult(name = "GetPerformancesByDateResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetPerformancesByDate", targetNamespace = "http://andipaetzold.de/", className = "services.GetPerformancesByDate")
    @ResponseWrapper(localName = "GetPerformancesByDateResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetPerformancesByDateResponse")
    public ArrayOfPerformance getPerformancesByDate(
        @WebParam(name = "dateTime", targetNamespace = "http://andipaetzold.de/")
        XMLGregorianCalendar dateTime);

    /**
     * 
     * @param artist
     * @return
     *     returns services.ArrayOfPerformance
     */
    @WebMethod(operationName = "GetUpcomingPerformancesByArtist", action = "http://andipaetzold.de/GetUpcomingPerformancesByArtist")
    @WebResult(name = "GetUpcomingPerformancesByArtistResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetUpcomingPerformancesByArtist", targetNamespace = "http://andipaetzold.de/", className = "services.GetUpcomingPerformancesByArtist")
    @ResponseWrapper(localName = "GetUpcomingPerformancesByArtistResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetUpcomingPerformancesByArtistResponse")
    public ArrayOfPerformance getUpcomingPerformancesByArtist(
        @WebParam(name = "artist", targetNamespace = "http://andipaetzold.de/")
        Artist artist);

    /**
     * 
     * @param artist
     * @return
     *     returns services.ArrayOfPerformance
     */
    @WebMethod(operationName = "GetPerformancesByArtist", action = "http://andipaetzold.de/GetPerformancesByArtist")
    @WebResult(name = "GetPerformancesByArtistResult", targetNamespace = "http://andipaetzold.de/")
    @RequestWrapper(localName = "GetPerformancesByArtist", targetNamespace = "http://andipaetzold.de/", className = "services.GetPerformancesByArtist")
    @ResponseWrapper(localName = "GetPerformancesByArtistResponse", targetNamespace = "http://andipaetzold.de/", className = "services.GetPerformancesByArtistResponse")
    public ArrayOfPerformance getPerformancesByArtist(
        @WebParam(name = "artist", targetNamespace = "http://andipaetzold.de/")
        Artist artist);

}
